
CREATE TRIGGER TRIGGER_EMAIL_HOST_AFTER_INSERT AFTER INSERT ON EMAIL_HOST FOR EACH ROW
BEGIN
DECLARE action VARCHAR(4);
set action = 'C';
INSERT INTO EMAIL_HOST_AUD
        (CODE,PROVIDER,HOST1,HOST2,REQUIRE_AUTH,SECURE_TYPE,PORT,
         PRIORITY,STATUS,EMAIL_SIZE_LIMIT,ACTION,ACTION_TIME)
         VALUES
        (NEW.CODE,NEW.PROVIDER,NEW.HOST1,NEW.HOST2,NEW.REQUIRE_AUTH,NEW.SECURE_TYPE,NEW.PORT,
         NEW.PRIORITY,NEW.STATUS,NEW.EMAIL_SIZE_LIMIT,action,CURRENT_TIMESTAMP);
END
GO

CREATE TRIGGER TRIGGER_EMAIL_HOST_AFTER_UPDATE AFTER UPDATE ON EMAIL_HOST FOR EACH ROW
BEGIN
DECLARE action VARCHAR(4);
set action = 'U';
INSERT INTO EMAIL_HOST_AUD
        (CODE,PROVIDER,HOST1,HOST2,REQUIRE_AUTH,SECURE_TYPE,PORT,
         PRIORITY,STATUS,EMAIL_SIZE_LIMIT,ACTION,ACTION_TIME)
         VALUES
        (NEW.CODE,NEW.PROVIDER,NEW.HOST1,NEW.HOST2,NEW.REQUIRE_AUTH,NEW.SECURE_TYPE,NEW.PORT,
         NEW.PRIORITY,NEW.STATUS,NEW.EMAIL_SIZE_LIMIT,action,CURRENT_TIMESTAMP);
END
GO

CREATE TRIGGER TRIGGER_EMAIL_HOST_AFTER_DELETE AFTER DELETE ON EMAIL_HOST FOR EACH ROW
BEGIN
DECLARE action VARCHAR(4);
set action = 'D';
INSERT INTO EMAIL_HOST_AUD
        (CODE,PROVIDER,HOST1,HOST2,REQUIRE_AUTH,SECURE_TYPE,PORT,
         PRIORITY,STATUS,EMAIL_SIZE_LIMIT,ACTION,ACTION_TIME)
         VALUES
        (OLD.CODE,OLD.PROVIDER,OLD.HOST1,OLD.HOST2,OLD.REQUIRE_AUTH,OLD.SECURE_TYPE,OLD.PORT,
         OLD.PRIORITY,OLD.STATUS,OLD.EMAIL_SIZE_LIMIT,action,CURRENT_TIMESTAMP);
END
GO




