
CREATE TRIGGER TRIGGER_SMS_PROVIDER_AFTER_INSERT AFTER INSERT ON SMS_PROVIDER FOR EACH ROW
BEGIN
DECLARE action VARCHAR(4);
set action = 'C';
INSERT INTO SMS_PROVIDER_AUD
        (SMS_PROVIDER_ID,PROVIDER_NAME,ENDPOINT_URL,HTTP_METHOD,USERNAME,PASSWORD,LONG_SMS,SPECIAL_CHARACTER,SEND_FOREIGN_COUNTRY,FAST_SMS,STATUS,REMARK,
        CREATE_DATE,CREATE_BY,UPDATE_DATE,UPDATE_BY,ACTION,ACTION_TIME)
         VALUES
        (NEW.ID,NEW.PROVIDER_NAME,NEW.ENDPOINT_URL,NEW.HTTP_METHOD,NEW.USERNAME,NEW.PASSWORD,NEW.LONG_SMS,NEW.SPECIAL_CHARACTER,NEW.SEND_FOREIGN_COUNTRY,NEW.FAST_SMS,NEW.STATUS,NEW.REMARK,
        NEW.CREATE_DATE,NEW.CREATE_BY,NEW.UPDATE_DATE,NEW.UPDATE_BY,action,CURRENT_TIMESTAMP);
END
GO

CREATE TRIGGER TRIGGER_SMS_PROVIDER_AFTER_UPDATE AFTER UPDATE ON SMS_PROVIDER FOR EACH ROW
BEGIN
DECLARE action VARCHAR(4);
set action = 'U';
INSERT INTO SMS_PROVIDER_AUD
        (SMS_PROVIDER_ID,PROVIDER_NAME,ENDPOINT_URL,HTTP_METHOD,USERNAME,PASSWORD,LONG_SMS,SPECIAL_CHARACTER,SEND_FOREIGN_COUNTRY,FAST_SMS,STATUS,REMARK,
        CREATE_DATE,CREATE_BY,UPDATE_DATE,UPDATE_BY,ACTION,ACTION_TIME)
         VALUES
        (NEW.ID,NEW.PROVIDER_NAME,NEW.ENDPOINT_URL,NEW.HTTP_METHOD,NEW.USERNAME,NEW.PASSWORD,NEW.LONG_SMS,NEW.SPECIAL_CHARACTER,NEW.SEND_FOREIGN_COUNTRY,NEW.FAST_SMS,NEW.STATUS,NEW.REMARK,
        NEW.CREATE_DATE,NEW.CREATE_BY,NEW.UPDATE_DATE,NEW.UPDATE_BY,action,CURRENT_TIMESTAMP);
END
GO

CREATE TRIGGER TRIGGER_SMS_PROVIDER_AFTER_DELETE AFTER DELETE ON SMS_PROVIDER FOR EACH ROW
BEGIN
DECLARE action VARCHAR(4);
set action = 'D';
INSERT INTO SMS_PROVIDER_AUD
        (SMS_PROVIDER_ID,PROVIDER_NAME,ENDPOINT_URL,HTTP_METHOD,USERNAME,PASSWORD,LONG_SMS,SPECIAL_CHARACTER,SEND_FOREIGN_COUNTRY,FAST_SMS,STATUS,REMARK,
        CREATE_DATE,CREATE_BY,UPDATE_DATE,UPDATE_BY,ACTION,ACTION_TIME)
         VALUES
        (OLD.ID,OLD.PROVIDER_NAME,OLD.ENDPOINT_URL,OLD.HTTP_METHOD,OLD.USERNAME,OLD.PASSWORD,OLD.LONG_SMS,OLD.SPECIAL_CHARACTER,OLD.SEND_FOREIGN_COUNTRY,OLD.FAST_SMS,OLD.STATUS,OLD.REMARK,
        OLD.CREATE_DATE,OLD.CREATE_BY,OLD.UPDATE_DATE,OLD.UPDATE_BY,action,CURRENT_TIMESTAMP);
END
GO




